theme: jekyll-theme-minimal
title: Definitely not NASA
description: Tbd as of now.
logo: assets/logo/main.jpg
show_downloads: "true"


plugins:
  - jekyll-analytics


##Google Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-117922683-1
    anonymizeIp: false
