theme: jekyll-theme-minimal
title: Definitely not NASA
description: Tbd as of now.
logo: assets/logo/main.jpg
show_downloads: "true"

# Google Analytics
google_analytics: UA-117922683-1


##plugins:
##  - jekyll-analytics


##Google Analytics
##  GoogleAnalytics:
##    id: UA-117922683-1
##    anonymizeIp: false
